### PR TITLE
Core: Fixes to Display.Capture on start up

### LINKED ISSUE #545: MacOS: crash with display.capture()
`display.capture` causes the simulator to crash on Corona version 3683 and newer. I am on a MacOS Ventura 13.3. I have a simple project with just the following code in main.lua
```lua
display.setDefault( "background", 1 )
local staticImageBack = display.newRect(400,400,400,400)
staticImageBack:setFillColor(1,0,0)
display.capture(staticImageBack, {captureOffscreenArea=true, saveToPhotoLibrary=false})
```

When run on version 3683 the simulator crashes instantly (90% of times...which is weird) while on older Corona versions it runs fine.

https://user-images.githubusercontent.com/130387/231262190-0f066365-a2b3-4462-8aae-767dcd4ee381.mov

[Display_Capture_Crash_on_v3683.zip](https://github.com/coronalabs/corona/files/11203935/Display_Capture_Crash_on_v3683.zip)

Created bug report from: [discord message](https://discord.com/channels/721785436195782677/724637134115438714/1094311572823887894).

### PR DESCRIPTION
**Pull request by scottrules44**
This should fix #545, the Sample Code

`
display.setDefault( "background", 1 )
local staticImageBack = display.newRect(400,400,400,400)
staticImageBack:setFillColor(1,0,0)
display.capture(staticImageBack, {captureOffscreenArea=true, saveToPhotoLibrary=false})
`

10 times and did not get a crash

### CODE REVIEW

**Comment by scottrules44** [comment]
Here is video here as well lol 
https://youtu.be/05I7WQbWozk

**Comment by elpida-v** [comment]
@scottrules44 Looks like you fixed it! Good job! 👍
Any chance you guys can push a release with this patch? I know you just published a release, but we need to submit our app update by tomorrow.

**Comment by elpida-v** [comment]
Unfortunately, the `display.capture` crash persists in the latest sim version **3690**. It crashes most of the times. The problem seems to have started on version 3683. As you can see on the video, **3682** does not have any issues with `display.capture`.

https://github.com/coronalabs/corona/assets/59620078/3d179eb8-423a-404a-b798-3665587c2560

**Review by Shchvova — APPROVED** [review]
🤞

**Pull request merged**
