### PR TITLE
Update Rtt_IPhoneWebViewObject.mm

### PR DESCRIPTION
**Pull request by cublah**
Allow local file access

### CODE REVIEW

**Comment by Shchvova** [comment]
Does this actually works?

**Comment by cublah** [comment]
Yes, it works, I’ve used it on about a dozen projects

**Comment by Shchvova** [comment]
Is there a possibility you would provide a demo app for this?

**Comment by Shchvova** [comment]
Hello!
I made changes so your code actually compiles and runs now. I still need an example project to test it.
To run your code on your own, check out the repo, and put your project  in `test\assets2`, so main.lua is `platform/test/assets2/main.lua`. Then open `platform/iphone/ratatouille.xcodeproj` and run the `template` target on device or simulator.

**Comment by Shchvova** [comment]
Here is what I did.  I created 2 html files linking to each other.
Lua code is
```lua
local webView = native.newWebView( display.contentCenterX, display.contentCenterY, display.actualContentWidth, display.actualContentHeight )
local f = system.pathForFile('index1.html')
webView:request( "file://" .. f )
```
I didn't see any changes after commenting out `[theConfiguration.preferences  setValue:@YES forKey:@"allowFileAccessFromFileURLs"];` you submitted.

I would love to merge your request, but I do not understand what issue does it solve. Also, you initial pull request did not compile.

Here is full sample I used to test: [WebViewTest.zip](https://github.com/coronalabs/corona/files/4196868/WebViewTest.zip).

**Comment by cublah** [comment]
This enables you load local files from the documents directory, now it’s possible Apple have fixed this the the the last couple of versions of iOS  but I know putting this in works on all versions, I’ve been using this in projects for the last 4 years and without it you can not read local files from the documents directory in all versions of iOS.

**Comment by solares** [comment]
I've found there are differences between a file in ResourceDirectory and one in CachesDirectory. I've edited your project to test both these cases. Can you try this pre- and post- WKWebView?

[WebViewTest.zip](https://github.com/coronalabs/corona/files/4204714/WebViewTest.zip)

**Comment by solares** [comment]
I did a simple test with this setup various iOS versions today. Here are the results: 

versions

**Comment by Shchvova** [comment]
I just tried your sample on 10.3, everything seems to work fine without your patch.

**Comment by solares** [comment]
I get this on 10.3.3, iPhone 6
Screen Shot 2020-02-15 at 3 32 53 PM

**Comment by solares** [comment]
And on iOS8, the other way around:
Screen Shot 2020-02-15 at 4 14 39 PM

I found this old thread which mentions `[WKWebView loadFileURL:allowingReadAccessToURL:]`, not quite same as cublah's `allowFileAccessFromFileURLs`.

https://stackoverflow.com/questions/24882834/wkwebview-not-loading-local-files-under-ios-8

**Comment by Shchvova** [comment]
OK.  Did anyone here actually was able to build Corona from this source code and see if `allowFileAccessFromFileURLs` fixes the issue? Because I couldn't reproduce the issue in Xcode simulator. I got it working quite well on all I tried.

**Comment by solares** [comment]
I have a more complicated web page which uses `require.js `to load scripts. This fails on `WKWebView` but works fine on `UIWebView`. 

I've been trying to get a minimal example to you but will take me some more time. 

I don't know how to build Corona from source. Is there a how-to for this?

**Comment by Shchvova** [comment]
@solares yes, of course. See [comment](https://github.com/coronalabs/corona/pull/36#issuecomment-585574295) above. First clone the repo though `git clone --recursive https://github.com/coronalabs/corona.git` or something

**Comment by solares** [comment]
I can build to Simulator but I'm stuck getting to device. Not an Xcode user, just a Corona user! I'll look around for a way to fix this and get back to you when I've tested. 

incidentally, once I am able to build in Xcode, would I be able to, for example, revert the WKWebView commit in order to get my app working in the short term, and build and release on Apple with my own personalised Corona SDK, or are the other steps involved in doing this?

**Comment by solares** [comment]
Here's a project that fails for me on iOS13 with WKWebView, but works fine with UIWebView. 

[WebViewTest.zip](https://github.com/coronalabs/corona/files/4208528/WebViewTest.zip)

It's similar to the last one, showing a webpage in ResourceDirectory at /info, and then the app copies the page to CachesDirectory at /info.

The Resources version works fine, but the Caches folder fails with this error (seen via Safari Debugger:

Screen Shot 2020-02-15 at 9 42 25 PM

Please test to see if the `allowFileAccessFromFileURLs` fixes this. Thanks.

**Comment by Shchvova** [comment]
Please, read the instructions. To test iOS you don't want to build simulator. You build iphone template. I'll check it tomorrow.

**Comment by solares** [comment]
I built on iPhone iOS 13.  The pull request did not work for me. 

I got it to work like this: 

Replace line 279:

`[fWebView loadRequest:request];` 

with 

`
NSURL *cachesURL = [[[NSFileManager defaultManager] URLsForDirectory:NSCachesDirectory inDomains:NSUserDomainMask] objectAtIndex:0];
[fWebView loadFileURL:request.URL allowingReadAccessToURL:cachesURL];
`
This works in the CachesDirectory but now fails in ResourceDirectory. Of course, we'd need to handle FileURLs separately from normal requests.

**Comment by Shchvova** [comment]
Thanks, @solares. I built up on your snippet and amended the PR. May I ask please to check if it works for you? Instructions on how to check it out locally can be found at the very top (search page for `Check out locally` button.

**Comment by solares** [comment]
Thanks @Shchvova. Works for me! I tried it on iOS 13, 12 and 10. 

iOS 8 still does not allow access to HTML in ResourceDirectory, but that's not a problem for me (might be for others?)

**Comment by Shchvova** [comment]
OK. For now I will merge in my changes. It is better than existing code. iOS8 support will come later.

**Pull request merged**
