### PR TITLE
iOS: Alternate Icon Support

### PR DESCRIPTION
**Pull request by scottrules44**

### CODE REVIEW

**Comment by scottrules44** [comment]
^ Note there is some code for Sticker Packing, but it needs to build out more

**Review by Shchvova — APPROVED** [review]

**Comment by Shchvova** [comment]
Good job. Alternative icons were working before but I guess they added more steps to it. Ugh.
Please make sure to document your changes. Thanks

**Comment by scottrules44** [comment]
Will do thanks!

**Comment by sekodev** [comment]
I'm also curious about that.

**Comment by sekodev** [comment]
> @scottrules44 Is there a guide on how to use this feature?

I'm also curious about that.

**Comment by clang-clang-clang** [comment]
May need update `platform/resources/valid_build_settings.lua` to remove warning.

**Pull request merged**
