### PR TITLE
MacOS: Fix crash with display.capture()

### LINKED ISSUE #545: MacOS: crash with display.capture()
`display.capture` causes the simulator to crash on Corona version 3683 and newer. I am on a MacOS Ventura 13.3. I have a simple project with just the following code in main.lua
```lua
display.setDefault( "background", 1 )
local staticImageBack = display.newRect(400,400,400,400)
staticImageBack:setFillColor(1,0,0)
display.capture(staticImageBack, {captureOffscreenArea=true, saveToPhotoLibrary=false})
```

When run on version 3683 the simulator crashes instantly (90% of times...which is weird) while on older Corona versions it runs fine.

https://user-images.githubusercontent.com/130387/231262190-0f066365-a2b3-4462-8aae-767dcd4ee381.mov

[Display_Capture_Crash_on_v3683.zip](https://github.com/coronalabs/corona/files/11203935/Display_Capture_Crash_on_v3683.zip)

Created bug report from: [discord message](https://discord.com/channels/721785436195782677/724637134115438714/1094311572823887894).

### PR DESCRIPTION
**Pull request by scottrules44**
Fixes #545

### CODE REVIEW

**Review by Shchvova — APPROVED** [review]
this doesn't really do anything. In Objective-C you can call messages (functions) on `nil` they return `nil`
But hey, lets merge it and see, may be some magic would happen...

**Comment by elpida-v** [comment]
So, it did fix it for you Scott?

**Comment by scottrules44** [comment]
Yes

**Comment by Shchvova** [comment]
We're trying to solve them asap

**Comment by elpida-v** [comment]
It's great that the crash was fixed, thanks! Hoping that the release will come out soon.

**Comment by clang-clang-clang** [comment]
> We hope so. But there are issues with build system blocking us releasing the new version at the moment

Hi, I found that the macOS compilation error in [GitHub Action](https://github.com/coronalabs/corona/actions/runs/4810296830/jobs/8562792175#step:6:1786) is very similar to the error I encountered when dealing with the iOS *plugin_openssl* (have not found a compatible solution):

After upgrading the *iOS Deployment Target* from `8.0` to `11.0` (the lowest version supported by Xcode 14.3), the error of `libarclite_*.a` not found will disappear because it is not linked by default, refer to [Apple Developer Forums - error](https://developer.apple.com/forums/thread/727527) and [CMake issues 19990](https://gitlab.kitware.com/cmake/cmake/-/issues/19990). Maybe it's time to bump up the version https://github.com/coronalabs/corona/pull/557? :O

Hope this can be helpful.

**Comment by scottrules44** [comment]
> > We hope so. But there are issues with build system blocking us releasing the new version at the moment
> 
> Hi, I found that the macOS compilation error in [GitHub Action](https://github.com/coronalabs/corona/actions/runs/4810296830/jobs/8562792175#step:6:1786) is very similar to the error I encountered when dealing with the iOS _plugin_openssl_ (have not found a compatible solution):
> 
> After upgrading the _iOS Deployment Target_ from `8.0` to `11.0` (the lowest version supported by Xcode 14.3), the error of `libarclite_*.a` not found will disappear because it is not linked by default, refer to [Apple Developer Forums - error](https://developer.apple.com/forums/thread/727527) and [CMake issues 19990](https://gitlab.kitware.com/cmake/cmake/-/issues/19990). Maybe it's time to bump up the version #557? :O
> 
> Hope this can be helpful.

Yeah, in my testing, MacOS need an update to MacOS 10.11 and iOS 11. I'm running lot's of tests on my branch
https://github.com/scottrules44/Solar2D-98

The current main issue is the Window cert needs to be renewed/replaced, and Microsoft does not make it easy

**Comment by clang-clang-clang** [comment]
It's good to hear that the problem can be solved! 😄 
However, the only thing we can do is wait for the issuer to take action...

**Pull request merged**
