### PR TITLE
Core: Fixes To Display Capture/Save Resolution 

### LINKED ISSUE #515: [Simulator]: Screenshots for some resolutions don't have exact size of the simulator resolution
**Describe the bug**
Screenshots for some resolutions don't have exact size of the simulator resolution.

**To Reproduce**
- Run simulator (in different resolutions)
- Save screenshot with: display.save(screen, {filename=screenshotName, baseDir=system.TemporaryDirectory, captureOffscreenArea=true})

** Samples **
* iPad 12,9“ - 2732 x 2048 Pixel - Standard Device --> width of screenshot is 1px plus (2733 x 2048)
* iPhone Plus 5,5“ - 2208 x 1242 Pixel - Custom Device --> width of screenshot is 1px minus (2207 x 1242)
* iPhone XS Max 6,5“ - 2688 x 1242 Pixel - Custom Device --> width of screenshot is 1px plus (2689 x 1242)

### PR DESCRIPTION
**Pull request by scottrules44**
This is aimed to fix #515 (and probably a few more) 
I tested this on my iPhone 14 Pro and iPad Air(which was originally wrong), and this gave me the correct image output resolution :) . Will try to test on more devices I have access to (including Android), but having trouble running `iPhone` "template" project on iOS simulators(get a bunch of undefined symbols).

### CODE REVIEW

**Comment by ggcrunchy** [comment]
@scottrules44 Sent you a DM in Discord about this.

**Comment by scottrules44** [comment]
I noticed when I switch to Android my Pixel 6a was off a bit, so I started over from scratch and based off @ggcrunchy comments(ty btw) I used more precise method for getting the width and height by passing Real/float values into "ContentToScreen". 
This work across every device mentioned perviously and my iPhone SE, Pixel 2XL, Pixel 6a, Kindle Fire,  and Samsung a025AZ. Very confident in this version

@Shchvova  It should be noted this won't breaking anything because I basically created a variant of ContentToScreen, one that take in reals/floats and one that takes ints. :)

**Comment by scottrules44** [comment]
This is the test I used btw
[assets2.zip](https://github.com/coronalabs/corona/files/10867323/assets2.zip)

**Review by Shchvova — APPROVED** [review]

**Comment by zero-meta** [comment]
@scottrules44 After this pull request, `display.colorSample` doesn't work as expected.

**Comment by scottrules44** [comment]
> @scottrules44 After this pull request, `display.colorSample` doesn't work as expected. I use MacOS simulator 3690. Here is my test example: [testColorSample.zip](https://github.com/coronalabs/corona/files/11439129/testColorSample.zip)
> 
> ```lua
> local bkg = display.newRect(display.contentCenterX, display.contentCenterY, display.contentWidth, display.contentHeight )
> bkg:setFillColor(1, 0, 0, 1)
> 
> local function onColorSample( event )
>     print( "Sampling pixel at position (" .. event.x .. "," .. event.y .. ")" )
>     print( "R = " .. event.r )
>     print( "G = " .. event.g )
>     print( "B = " .. event.b )
>     print( "A = " .. event.a )
> end
>  
> timer.performWithDelay(100, function()
>     display.colorSample( display.contentCenterX, display.contentCenterY, onColorSample )
> end)
> ```
> 
> Now it always print R = 0, G = 0, B = 0, A = 0. And I found the output depends on what `width, height` value set in `config.lua`. If I set `width = 320, height = 480`, it will get correct color.
> 
> ```lua
> application =
> {
>     content = 
>     { 
>         fps = 60,
>         width = 1536,
>         height = 2048,
>         scale = "letterbox",
>         xAlign = "center",
>         yAlign = "center",
>     }
> }
> ```

Fixed with #575
I get 
R = 1
G = 0
B = 0
A = 1

**Pull request merged**
