### PR TITLE
Maintenance Pt2

### PR DESCRIPTION
**Pull request by scottrules44**

### CODE REVIEW

**Comment by Shchvova** [comment]
What happens here?

**Comment by scottrules44** [comment]
Saw there was a linking issue with Mac networking plugin

**Comment by scottrules44** [comment]
https://github.com/coronalabs/corona/actions/runs/6525565913/job/17718418138#step:6:931

**Comment by Shchvova** [comment]
I have #637 already, but building off that branch fails. Did you try to see if fix works?

**Comment by Shchvova** [comment]
If you explore you'll see that `network` is not a dependency in the log you linked
```
    Target 'CoronaCards' in project 'ratatouille'
        ➜ Explicit dependency on target 'ALmixer' in project 'ratatouille'
        ➜ Explicit dependency on target 'liblpeg' in project 'lpeg'
        ➜ Explicit dependency on target 'car' in project 'car'
        ➜ Explicit dependency on target 'lua' in project 'lua'
        ➜ Explicit dependency on target 'luac' in project 'lua'
        ➜ Explicit dependency on target 'plugins' in project 'plugins'
        ➜ Explicit dependency on target 'Box2D' in project 'ratatouille'
        ➜ Explicit dependency on target 'libluasocket' in project 'lua'
        ➜ Explicit dependency on target 'liblua' in project 'ratatouille'
        ➜ Explicit dependency on target 'librtt' in project 'ratatouille'
        ➜ Explicit dependency on target 'luafilesystem' in project 'ratatouille'
        ➜ Explicit dependency on target 'tachyon' in project 'libtachyon'
```

when I build locally, I get same output except with network.dylib in the dependency list and everything works. Did you figure out what the issue is?

**Pull request closed without merging**
