### PR TITLE
Apple: Fixes for networking for iOS 17 and MacOS 14

### PR DESCRIPTION
**Pull request by scottrules44**

### CODE REVIEW

**Comment by scottrules44** [comment]
Fix based on #634

**Review by Shchvova — APPROVED** [review]

**Review by Shchvova — COMMENTED** [review]
I think this will leak memory. Let me tinker with

**Comment by Shchvova** [comment]
In future please try to avoid making PRs from your `master`. It messes with repos (mostly yours)

**Comment by Shchvova** [comment]
I accidentally merged this PR, actual fix is in 11bff30cb83b1d73b742f76c33340a98319176d1

**Comment by clang-clang-clang** [comment]
It works.
Your solution is better, but strangely it didn't work when I tested `retian` only for `fRequestURL` :(, however I incorrectly assumed that ARC would automatically reclaim the `copy` object.
Test case passed on iOS 17 and macOS Sonoma built with Xcode 15. 
Thank you. close #634.

**Pull request merged**
