### PR TITLE
Native: Fixes for Downloading Solar2D Plugins

### PR DESCRIPTION
**Pull request by scottrules44**

### CODE REVIEW

**Comment by Shchvova** [comment]
I am not so sure about this particular PR. This code was written long before we had offline builds on client machines. Would make sense to rewrite this code to use 
```lua
local pluginCollector = require "CoronaBuilderPluginCollector"
local collectorParams = { 
  pluginPlatform = platform,
  plugins = buildSettings.plugins or {},
  destinationDirectory = tmpDir,
  build = buildRevision,
  extractLocation = pluginDstDir,
}
pluginCollector.collect(collectorParams)
```
Which would download using all the collectors, and following dependencies.
I think there are all pieces of code for downloading, but generating xcconfig-s would have to be re-done. Also, no need to write this code to support Android anymore, since it has this functionality in gradle script already.

**Comment by scottrules44** [comment]
@Shchvova Gotcha just implemented and tested 👍

**Review by Shchvova — APPROVED** [review]

**Comment by Shchvova** [comment]
Lets submit this first version then we would iterate on it.

**Comment by labolado** [comment]
It seems that the filtering mechanism of the plugin has been compromised. I am compiling an iOS app, but I keep getting an error that it cannot open an Android plugin.

`PhaseScriptExecution Download\ Plugins /Users/test/Library/Developer/Xcode/DerivedData/App1-dkmfbkuviwxlohbweychsgqhsobm/Build/Intermediates.noindex/App1.build/Debug-maccatalyst/Download\ Plugins.build/Script-F597AC721ED8CA480085F5E5.sh (in target 'Download Plugins' from project 'App1')
    cd /Users/test/data/dev/app/test/src/ios_free
    /bin/sh -c /Users/test/Library/Developer/Xcode/DerivedData/App1-dkmfbkuviwxlohbweychsgqhsobm/Build/Intermediates.noindex/App1.build/Debug-maccatalyst/Download\\\ Plugins.build/Script-F597AC721ED8CA480085F5E5.sh
tar: Error opening archive: Failed to open '/Users/test/Library/Application Support/Corona/Native Plugins/iphone/plugin.steamworks/data.tgz'
true
nil
ERROR: unable to unpack plugin plugin.steamworks (com.coronalabs).
Exiting due to errors (above)
Command PhaseScriptExecution failed with a nonzero exit code

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Download\ Plugins /Users/test/Library/Developer/Xcode/DerivedData/App1-dkmfbkuviwxlohbweychsgqhsobm/Build/Intermediates.noindex/App1.build/Debug-maccatalyst/Download\ Plugins.build/Script-F597AC721ED8CA480085F5E5.sh (in target 'Download Plugins' from project 'App1')
(1 failure)`

**Comment by zero-meta** [comment]
@scottrules44 When I try ios native build with *android only* plugin setting in `build.settings`, It will failed.
Such as:
```lua
plugins =
{
    ["plugin.tts"] = {
        publisherId = "com.coronalabs",
    },
    ["plugin.zip"] = {
        publisherId = "com.coronalabs"
    }
}
```
`plugin.tts` only supports android platform. It should be auto ignored on ios native build.
And I also tried supportedPlatforms setting, It failed with error:
`tar: Error opening archive: Failed to open '/Users/xxx/Library/Application Support/Corona/Native Plugins/iphone/plugin.tts/data.tgz'`
```lua
plugins =
{
    ["plugin.tts"] = {
        publisherId = "com.coronalabs",
        supportedPlatforms = {
            ["android"] = {url = "xxx"},
        }
    },
    ["plugin.zip"] = {
        publisherId = "com.coronalabs"
    }
}
```

**Pull request merged**
